export const CREATE_ASSIGNMENTS = "EM001";
export const EDIT_ASSIGNMENTS = "EM002";
export const DELETE_ASSIGNMENTS = "EM003";
export const EDIT_PROFILE = "EM004";
export const CREATE_ASSIGNMENTS_TEMPLATES = "EM005";
export const EDIT_ASSIGNMENTS_TEMPLATES = "EM006";
export const DELETE_ASSIGNMENTS_TEMPLATES = "EM007";

