import CachedIcon from "@material-ui/icons/Cached";
import DoneIcon from "@material-ui/icons/Done";
import AssignmentTurnedInOutlinedIcon from "@material-ui/icons/AssignmentTurnedInOutlined";
import HourglassEmptyOutlinedIcon from "@material-ui/icons/HourglassEmptyOutlined";
import React from "react";

export const text = {
  english: {
    settings: {
      direction: "ltr",
    },

    LANGUAGE_LOADING:'Language is loading...',
    pending:'Pending',
    in_progress:'In progress',
    done:'Done',
    LAST_UPDATED:'Last updated',
    CREATE_ASSIGNMENTS: "Create assignments",
    EDIT_ASSIGNMENTS: "Edit assignments",
    DELETE_ASSIGNMENTS: "Delete assignments",
    EDIT_PROFILE: "Edit profile",
    EMPLOYEE_PERMISSIONS: "Employee Permissions",
    PROFILE: "Profile",
    PERMISSIONS: "Permissions",
    SYSTEM: "System",
    NO_ASSIGNMENTS: "No assignments",
    ASSIGNMENT_CREATE_SUCCESS: "Assignment created",
    LOGOUT: "Logout",
    LANGUAGE_SELECT: "System language",
    NO_TEMPLATES: "No templates",
    SETTINGS: "Settings",
    EMPLOYEES: "Employees",
    CREATE_EMPLOYEE_BTN: "CREATE EMPLOYEE",
    EDIT_EMPLOYEE: "Edit Employee",
    CREATE_EMPLOYEE: "Create Employee",
    EMPLOYEES_TITLES: ["Name", "Pending", "In progress", "Done"],
    NAME: "Name",
    pending: "Pending",
    in_progress: "In progress",
    done: "Done",
    NEW_EMPLOYEE: "Create Employee",
    EMAIL: "Email",
    PHONE: "Phone",
    POSITION: "Position",
    PASSWORD: "Password",
    COPY: "Copy",
    COPIED: "Copied",
    GENERATE: "Generate",
    GENERATED: "Generated",
    SAVE: "Save",
    CANCEL: "Cancel",
    YES: "Yes",
    NO: "No",
    RESET: "Reset",
    INVALID_PHONE: "Invalid Phone",
    INVALID_EMAIL: "Invalid Email",
    REQUIRED_FIELD: "Required Field",
    EMPLOYEE_PAGE: "Employee Page",
    EDIT: "Edit",
    CREATE: "Create",
    DELETE: "Delete",
    REMOVE_TEXT: "Are you sure, you want to remove:",
    REMOVE_ASSIGNMENT_QUESTION:'Delete the assignment',
    NO_EMPLOYEES: "No Employees",
    ASSIGNMENTS: "Assignments",
    ASSIGNMENT: "Assignment",
    PERSONAL_ASSIGNMENTS:'Personal',
    ADD_FILE: "Add file",
    SELECT_DATE: "Select Date",
    EMPLOYEE_INFO: "Employee info",
    STATUS: "Status",
    TITLE: "Title",
    TEXT: "Text",
    DEADLINE: "Deadline",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    TEMPLATES: "Templates",
    NEW_ASSIGNMENT: "Create Assignment",
    EMPLOYEE_ASSIGNMENTS_TITLES: [{name:"Title", value:'title'}, {name:"Deadline", value:'deadline'},{name: "Actions", value:'actions'}],
    VIEW: "View",
    MARK_AS_PENDING: "Mark as pending",
    MARK_AS_DONE: "Mark as done",
    MARK_AS_PROGRESS: "Mark as in progress",
    REMOVE: "Remove",
    CONTENT: "Content",
    FILES: "Files",
    COMMENTS: "Comments",
    COMMENT: "Comment",
    CLOSE: "Close",
    ASSIGNMENT_STATUS_ARR: [
      {
        text: "Pending",
        value: "pending",
        img: <HourglassEmptyOutlinedIcon />,
      },
      {
        text: "In progress",
        value: "in_progress",
        img: <CachedIcon />,
      },
      {
        text: "Done",
        value: "done",
        img: <DoneIcon />,
      },
    ],
  },
  hebrew: {
    settings: {
      direction: "rtl",
    },
    LANGUAGE_LOADING:'השפה נטענת...',
    pending:'ממתין',
    in_progress:'בתהליך',
    done:'בוצע',
    LAST_UPDATED:'עודכן לאחרונה',
    CREATE_ASSIGNMENTS: "יצירת משימות",
    EDIT_ASSIGNMENTS: "עריכת משימות",
    DELETE_ASSIGNMENTS: "מחיקת משימות",
    EDIT_PROFILE: "עריכת פרופיל",
    EMPLOYEE_PERMISSIONS: "הרשאות עובד",
    PROFILE: "משתמש",
    PERMISSIONS: "הרשאות",
    SYSTEM: "מערכת",
    NO_ASSIGNMENTS: "אין משימות",
    CLOSE: "סגור",
    ASSIGNMENT_CREATE_SUCCESS: "תבנית נוצרה בהצלחה",
    LOGOUT: "התנתק",
    LANGUAGE_SELECT: "שפת מערכת",
    NO_TEMPLATES: "אין תבניות",
    SETTINGS: "הגדרות",
    EMPLOYEES: "עובדים",
    CREATE_EMPLOYEE_BTN: "צור עבד",
    EDIT_EMPLOYEE: "ערוך עובד",
    CREATE_EMPLOYEE: "צור עובד",
    EMPLOYEES_TITLES: ["שם", "ממתין", "בתהליך", "בוצע"],
    NAME: "שם",
    NEW_EMPLOYEE: "צור עובד",
    EMAIL: "מייל",
    PHONE: "טלפון",
    POSITION: "עמדה",
    PASSWORD: "סיסמא",
    COPY: "העתק",
    COPIED: "בוצע",
    GENERATE: "צור",
    GENERATED: "בוצע",
    SAVE: "שמור",
    CANCEL: "בטל",
    YES: "כן",
    NO: "לא",
    RESET: "אפס",
    INVALID_PHONE: "טלפון לא תקין",
    INVALID_EMAIL: "אימייל שגוי",
    REQUIRED_FIELD: "שדה חובה",
    EMPLOYEE_PAGE: "עמוד עובד",
    EDIT: "ערוך",
    PERSONAL_ASSIGNMENTS:'משימות שלי',
    CREATE: "צור",
    DELETE: "מחק",
    REMOVE_TEXT: "האם למחוק את",
    REMOVE_ASSIGNMENT_QUESTION:'האם למחוק את',
    NO_EMPLOYEES: "אין עובדים",
    ASSIGNMENTS: "משימות",
    ASSIGNMENT: "משימה",
    ADD_FILE: "הוסף קובץ",
    SELECT_DATE: "בחר תאריך",
    EMPLOYEE_INFO: "מידע על עובד",
    STATUS: "סטטוס",
    TITLE: "כותרת",
    TEXT: "טקסט",
    DEADLINE: "מועד אחרון",
    ACTIVE: "פעיל",
    INACTIVE: "אינו פעיל",
    TEMPLATES: "תבניות",
    NEW_ASSIGNMENT: "צור משימה",
    EMPLOYEE_ASSIGNMENTS_TITLES: [{name:"כותרת", value:'title'}, {name:"יעד אחרון", value:'deadline'},{name: "פעולות", value:'actions'}],
    VIEW: "צפה במשימה",
    MARK_AS_PENDING: "סמן כממתין",
    MARK_AS_DONE: "סמן כבוצע",
    MARK_AS_PROGRESS: "סמן כמתבצע",
    REMOVE: "מחק",
    CONTENT: "תוכן",
    FILES: "קבצים",
    COMMENTS: "הערות",
    COMMENT: "הערה",
    ASSIGNMENT_STATUS_ARR: [
      {
        text: "ממתין",
        value: "pending",
        img: <HourglassEmptyOutlinedIcon />,
      },
      {
        text: "בתהליך",
        value: "in_progress",
        img: <CachedIcon />,
      },
      {
        text: "בוצע",
        value: "done",
        img: <DoneIcon />,
      },
    ],
  },
};
